services:
  zako-issuetracker:
    image: zako-issuetracker
    build:
      context: .
      dockerfile: zako-issuetracker/Dockerfile
    environment:
      DISCORD_TOKEN:
      SQLITE_FILE: /data/zako.sqlite
      ADMIN_IDS:
      EMBED_PAGE_SIZE: 5
      IMG_LINK: https://cdn.discordapp.com/avatars/1365312197613453322/43da9fd0741f4657f2344deb2062c0ca.png
    volumes:
      - ./data:/data:rw
