services:
  zako-issuetracker:
    image: zako-issuetracker
    build:
      context: .
      dockerfile: zako-issuetracker/Dockerfile
    environment:
      DISCORD_TOKEN: 
      SQLITE_PATH: /data/zako.sqlite
      ADMIN_IDS: 
    volumes:
      - ./data:/data
